/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as MetodologiaRouteImport } from './routes/metodologia'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as SegmentosIndexRouteImport } from './routes/segmentos.index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'
import { Route as SegmentosSlugRouteImport } from './routes/segmentos.$slug'
import { Route as CasesSlugRouteImport } from './routes/cases.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodologiaRoute = MetodologiaRouteImport.update({
  id: '/metodologia',
  path: '/metodologia',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosIndexRoute = SegmentosIndexRouteImport.update({
  id: '/segmentos/',
  path: '/segmentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/servicos/$slug',
  path: '/servicos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentosSlugRoute = SegmentosSlugRouteImport.update({
  id: '/segmentos/$slug',
  path: '/segmentos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/metodologia': typeof MetodologiaRoute
  '/sobre': typeof SobreRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/segmentos/$slug': typeof SegmentosSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/cases/': typeof CasesIndexRoute
  '/segmentos/': typeof SegmentosIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/metodologia': typeof MetodologiaRoute
  '/sobre': typeof SobreRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/segmentos/$slug': typeof SegmentosSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/cases': typeof CasesIndexRoute
  '/segmentos': typeof SegmentosIndexRoute
  '/servicos': typeof ServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/metodologia': typeof MetodologiaRoute
  '/sobre': typeof SobreRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/segmentos/$slug': typeof SegmentosSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/cases/': typeof CasesIndexRoute
  '/segmentos/': typeof SegmentosIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/equipe'
    | '/metodologia'
    | '/sobre'
    | '/cases/$slug'
    | '/segmentos/$slug'
    | '/servicos/$slug'
    | '/cases/'
    | '/segmentos/'
    | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/equipe'
    | '/metodologia'
    | '/sobre'
    | '/cases/$slug'
    | '/segmentos/$slug'
    | '/servicos/$slug'
    | '/cases'
    | '/segmentos'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/equipe'
    | '/metodologia'
    | '/sobre'
    | '/cases/$slug'
    | '/segmentos/$slug'
    | '/servicos/$slug'
    | '/cases/'
    | '/segmentos/'
    | '/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  EquipeRoute: typeof EquipeRoute
  MetodologiaRoute: typeof MetodologiaRoute
  SobreRoute: typeof SobreRoute
  CasesSlugRoute: typeof CasesSlugRoute
  SegmentosSlugRoute: typeof SegmentosSlugRoute
  ServicosSlugRoute: typeof ServicosSlugRoute
  CasesIndexRoute: typeof CasesIndexRoute
  SegmentosIndexRoute: typeof SegmentosIndexRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodologia': {
      id: '/metodologia'
      path: '/metodologia'
      fullPath: '/metodologia'
      preLoaderRoute: typeof MetodologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/': {
      id: '/segmentos/'
      path: '/segmentos'
      fullPath: '/segmentos/'
      preLoaderRoute: typeof SegmentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/servicos/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segmentos/$slug': {
      id: '/segmentos/$slug'
      path: '/segmentos/$slug'
      fullPath: '/segmentos/$slug'
      preLoaderRoute: typeof SegmentosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  EquipeRoute: EquipeRoute,
  MetodologiaRoute: MetodologiaRoute,
  SobreRoute: SobreRoute,
  CasesSlugRoute: CasesSlugRoute,
  SegmentosSlugRoute: SegmentosSlugRoute,
  ServicosSlugRoute: ServicosSlugRoute,
  CasesIndexRoute: CasesIndexRoute,
  SegmentosIndexRoute: SegmentosIndexRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
